python3 main.py net_1 0 -optimizer Adam
python3 main.py net_1 0 -optimizer SGD
python3 main.py net_1 1 -optimizer Adam
python3 main.py net_1 1 -optimizer SGD
python3 main.py net_1_double 0 -optimizer Adam
python3 main.py net_1_double 0 -optimizer SGD
python3 main.py net_1_double 1 -optimizer Adam
python3 main.py net_1_double 1 -optimizer SGD
python3 main.py net_1_triple 0 -optimizer Adam
python3 main.py net_1_triple 0 -optimizer SGD
python3 main.py net_1_triple 1 -optimizer Adam
python3 main.py net_1_triple 1 -optimizer SGD
python3 main.py net_2 0 -optimizer Adam
python3 main.py net_2 0 -optimizer SGD
python3 main.py net_2 1 -optimizer Adam
python3 main.py net_2 1 -optimizer SGD
python3 main.py net_2_double 0 -optimizer Adam
python3 main.py net_2_double 0 -optimizer SGD
python3 main.py net_2_double 1 -optimizer Adam
python3 main.py net_2_double 1 -optimizer SGD
python3 main.py net_2_triple 0 -optimizer Adam
python3 main.py net_2_triple 0 -optimizer SGD
python3 main.py net_2_triple 1 -optimizer Adam
python3 main.py net_2_triple 1 -optimizer SGD
python3 main.py net_3 0 -optimizer Adam
python3 main.py net_3 0 -optimizer SGD
python3 main.py net_3 1 -optimizer Adam
python3 main.py net_3 1 -optimizer SGD
python3 main.py net_3_double 0 -optimizer Adam
python3 main.py net_3_double 0 -optimizer SGD
python3 main.py net_3_double 1 -optimizer Adam
python3 main.py net_3_double 1 -optimizer SGD
python3 main.py net_3_triple 0 -optimizer Adam
python3 main.py net_3_triple 0 -optimizer SGD
python3 main.py net_3_triple 1 -optimizer Adam
python3 main.py net_3_triple 1 -optimizer SGD
